apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaproducer
  template:
      metadata:
        labels:
          app: kafkaproducer
      spec:
        containers:
        - name: kafkaproducer
          image: gcr.io/alien-walker-373503/kafka_producer:latest